### ISSUE TITLE
Add HTTP headers to ws connection

### ISSUE THREAD

**Issue by deepeerie** [mat-sz/typesocket#1]
Like: const ws = new WebSocket('wss://example.com/socket', 'protocol', { headers: { 'Custom-Header': 'value' } });

**Comment by mat-sz** [comment]
@eiire The [WebSocket object](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) doesn't support extra headers. You can set a cookie before creating an instance of TypeScript, though.

You can change the value of the `Authorization` header by setting the username/password inside of the URL: `ws://username:password@example.com`.
